#!/bin/zsh

#set time output to seconds
TIMEFMT='%*E'

#create JSON object to hold results
results='{}'
#min time, lang
minTime=999999
fastest=Plankalkul

#C
gcc sorts/sort.c -o sort
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.C = $t')
rm sort

#C++
g++ sorts/sort.cpp -o sort
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '."C++" = $t')
rm sort

#C#
t=$( { time (dotnet run sorts/sort.cs;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '."C#" = $t')

#Dart
t=$( { time (dart run sorts/sort.dart;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Dart = $t')

#Haskell
ghc sorts/sort.hs > /dev/null 2>&1
t=$( { time (./sorts/sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Haskell = $t')
rm sorts/*.hi sorts/*.o sorts/sort

#Java
javac sorts/sort.java
t=$( { time (java sorts.sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Java = $t')
rm sorts/sort.class

#Javascript
t=$( { time (node sorts/sort.js;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Javascript = $t')

#LISP
t=$( { time (sbcl --script sorts/sort.lisp;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.LISP = $t')

#Python
t=$( { time (python sorts/sort.py;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Python = $t')

#R
t=$( { time (rscript sorts/sort.r  > /dev/null 2>&1;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.R = $t')

#Rust
rustc sorts/sort.rs
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Rust = $t')
rm sort

#Swift
t=$( { time (swift sorts/sort.swift;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Swift = $t')

#Zig
t=$( { time (zig run sorts/sort.zig;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Zig = $t')

#Zsh
t=$( { time (./sorts/sort.sh;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Zsh = $t')

#print all values
echo "$results" | jq -r 'to_entries[] | "\(.key): \(.value)"'

#builtin, verbose
