#!/bin/zsh

#set time output to seconds
TIMEFMT='%*E'

#create JSON object to hold results
results='{}'
#min time, lang
minTime=999999
fastest=Plankalkul

#Actionscript 3
if [[ -f "builtin/application.xml" ]]; then
    amxmlc builtin/sort.as > /dev/null 2>&1
    t=$( { time (adl builtin/application.xml > /dev/null 2>&1;) } 2>&1 )
    results=$(echo "$results" | jq --arg t "$t" '."Actionscript 3" = $t')
    rm -rf builtin/bin
    rm builtin/*.swf
fi

#APL
t=$( { time (apl -f builtin/sort.apl > /dev/null 2>&1;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.APL = $t')
rm .apl.history

#Bash
t=$( { time (./builtin/sort.bash;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Bash = $t')

#C
gcc builtin/sort.c -o sort
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.C = $t')
rm sort

#C++
g++ builtin/sort.cpp -o sort
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '."C++" = $t')
rm sort

#C#
t=$( { time (dotnet run builtin/sort.cs;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '."C#" = $t')

#COBOL
cobc -x builtin/sort.cobol
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.COBOL = $t')
rm sort

#Dart
t=$( { time (dart run builtin/sort.dart;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Dart = $t')

#Fortran
gfortran \
  -I/usr/local/include/fortran_stdlib/GNU-16.2.0 \
  builtin/sort.f90 \
  -L/usr/local/lib \
  -lfortran_stdlib_sorting \
  -lfortran_stdlib_bitsets \
  -lfortran_stdlib_strings \
  -lfortran_stdlib_core \
  -o sort
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Fortran = $t')
rm sort

#Haskell
ghc builtin/sort.hs > /dev/null 2>&1
t=$( { time (./builtin/sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Haskell = $t')
rm builtin/*.hi builtin/*.o builtin/sort

#HolyC
hcc --install-dir=/opt/homebrew/ builtin/sort.HC > /dev/null 2>&1
t=$( { time (./a.out;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.HolyC = $t')
rm a.out

#Java
javac builtin/sort.java
t=$( { time (java builtin.sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Java = $t')
rm builtin/sort.class

#Javascript
t=$( { time (node builtin/sort.js;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Javascript = $t')

#LISP
t=$( { time (sbcl --script builtin/sort.lisp;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.LISP = $t')

#Lua
t=$( { time (lua builtin/sort.lua;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Lua = $t')

#Python
t=$( { time (python builtin/sort.py;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Python = $t')

#R
t=$( { time (rscript builtin/sort.r  > /dev/null 2>&1;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.R = $t')

#Rust
rustc builtin/sort.rs
t=$( { time (./sort;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Rust = $t')
rm sort

#Scala
t=$( { time (scala builtin/sort.scala > /dev/null 2>&1;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Scala = $t')
rm -rf builtin/.bsp builtin/.scala-build

#SQL
if [[ -f "builtin/.env" ]]; then
    t=$( { time (mysql -u root -p$(head -n 1 builtin/.env) $(sed -n '2p' builtin/.env) < builtin/sort.sql > /dev/null 2>&1;) } 2>&1)
    results=$(echo "$results" | jq --arg t "$t" '.SQL = $t')
fi

#Swift
t=$( { time (swift builtin/sort.swift;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Swift = $t')

#Typescript
t=$( { time (node "builtin/sort.ts ";) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Typescript = $t')

#Visual Basic
if [[ -f "builtin/sort.vbproj" ]]; then
    t=$( { time (dotnet run --project=builtin;) } 2>&1 )
    results=$(echo "$results" | jq --arg t "$t" '."Visual Basic" = $t')
    rm -rf builtin/bin builtin/obj
fi

#Zig
t=$( { time (zig run builtin/sort.zig;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Zig = $t')

#Zsh
t=$( { time (./builtin/sort.zsh;) } 2>&1 )
results=$(echo "$results" | jq --arg t "$t" '.Zsh = $t')

#print all values
#echo "$results" | jq -r 'to_entries[] | "\(.key): \(.value)"'

#print all values, fastest to slowest
echo "$results" | jq -r 'to_entries | sort_by(.value)[] | "\(.key): \(.value)"'

#builtin, verbose
